mod actions;
mod app_layout;
mod app_layout_builder;
pub(crate) mod app_loop;
pub(crate) mod app_loop_fullview;
pub(crate) mod app_loop_inline;
mod app_main;
mod app_main_fullview;
mod app_main_inline;
pub(crate) mod app_state;
mod clipboard;
pub mod colors;
mod component;
pub mod components;
mod events;
mod handler_result;
pub mod handlers;
pub(crate) mod header;
pub mod init_permission;
pub(crate) mod input_handler;
mod layout;
mod layout_builder;
pub mod markdown;
mod message_renderer;
pub mod modes;
pub mod scroll_state;
pub mod setup;
pub mod terminal;
mod text_utils;

pub use app_main::run_with_session;
pub use app_main_fullview::run_with_session_fullview;
pub use app_main_inline::run_with_session_inline;
pub use colors::palette;
pub use message_renderer::MessageRenderer;
