mod actions;
mod app_layout;
mod app_layout_builder;
mod app_loop;
mod app_main;
mod app_state;
mod clipboard;
mod component;
pub mod components;
mod events;
mod handler_result;
pub mod handlers;
mod header;
mod init_permission_layout;
mod init_permission_loop;
mod input_handler;
mod layout;
mod layout_builder;
mod message_renderer;
pub mod setup;
pub mod terminal;

pub use app_main::run;
pub use message_renderer::MessageRenderer;
